#!/bin/bash

# Check if the directory path is provided as an argument
if [[ $# -eq 0 ]]; then
    echo "Please, enter the directory name"
    exit 1
fi

# Store the directory path provided as an argument
directory_path=$1

# Check if the specified directory exists
if [[ ! -d $directory_path ]]; then
    echo "Error: Directory '$directory_path' does not exist."
    exit 1
fi

# Create a timestamp for the backup file name
timestamp=$(date +%Y%m%d%H%M%S)

# Set the backup directory path
backup_directory="/path/to/backup/directory"

# Create the backup directory if it doesn't exist
if [[ ! -d $backup_directory ]]; then
    mkdir -p "$backup_directory"
fi

# Generate the backup file name
backup_filename="backup_${timestamp}.tar.gz"

# Perform the backup
tar -czf "${backup_directory}/${backup_filename}" "$directory_path"

# Check if the backup was successful
if [[ $? -eq 0 ]]; then
    echo "Backup of '$directory_path' created successfully: ${backup_directory}/${backup_filename}"
else
    echo "Error: Backup creation failed."
fi

echo "0 6 * * * /path/to/backup_script.sh /path/to/directory" >> /etc/crontab

# OR you can write "crontab -e" command and write " 0 6 * * * /path/to/backup_script.sh /path/to/directory" in it 
